#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Aug 16, 2021 02:02:27 AM PKT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pdf_jpg_converter

global conversion_mode
conversion_mode = "pdf"


def init(top, gui, mode, *args, **kwargs):
    global w, top_level, root, conversion_mode
    w = gui
    top_level = top
    root = top
    conversion_mode = mode


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def convert_again():
    destroy_window()
    global conversion_mode
    pdf_jpg_converter.vp_start_gui("pdf" if conversion_mode == "pdf" else "jpg")


def convert_opposite():
    destroy_window()
    global conversion_mode
    pdf_jpg_converter.vp_start_gui("jpg" if conversion_mode == "pdf" else "pdf")




